// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

package netmsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Message_Type int32

const (
	Message_TEST          Message_Type = 0
	Message_WAY           Message_Type = 1
	Message_REQ_WAY       Message_Type = 2
	Message_ACK_WAY       Message_Type = 3
	Message_REQ_ROOM_LIST Message_Type = 4
	Message_ACK_ROOM_LIST Message_Type = 5
	Message_REQ_ROOM_JOIN Message_Type = 6
	Message_ACK_ROOM_JOIN Message_Type = 7
)

var Message_Type_name = map[int32]string{
	0: "TEST",
	1: "WAY",
	2: "REQ_WAY",
	3: "ACK_WAY",
	4: "REQ_ROOM_LIST",
	5: "ACK_ROOM_LIST",
	6: "REQ_ROOM_JOIN",
	7: "ACK_ROOM_JOIN",
}

var Message_Type_value = map[string]int32{
	"TEST":          0,
	"WAY":           1,
	"REQ_WAY":       2,
	"ACK_WAY":       3,
	"REQ_ROOM_LIST": 4,
	"ACK_ROOM_LIST": 5,
	"REQ_ROOM_JOIN": 6,
	"ACK_ROOM_JOIN": 7,
}

func (x Message_Type) String() string {
	return proto.EnumName(Message_Type_name, int32(x))
}

func (Message_Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0, 0}
}

type Message struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}
func (*Message) Descriptor() ([]byte, []int) {
	return fileDescriptor_c06e4cca6c2cc899, []int{0}
}

func (m *Message) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Message.Unmarshal(m, b)
}
func (m *Message) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Message.Marshal(b, m, deterministic)
}
func (m *Message) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Message.Merge(m, src)
}
func (m *Message) XXX_Size() int {
	return xxx_messageInfo_Message.Size(m)
}
func (m *Message) XXX_DiscardUnknown() {
	xxx_messageInfo_Message.DiscardUnknown(m)
}

var xxx_messageInfo_Message proto.InternalMessageInfo

func init() {
	proto.RegisterEnum("netmsg.Message_Type", Message_Type_name, Message_Type_value)
	proto.RegisterType((*Message)(nil), "netmsg.Message")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor_c06e4cca6c2cc899) }

var fileDescriptor_c06e4cca6c2cc899 = []byte{
	// 154 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0x4b, 0x2d, 0xc9, 0x2d, 0x4e, 0x57, 0xea, 0x62,
	0xe4, 0x62, 0xf7, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x55, 0xaa, 0xe7, 0x62, 0x09, 0xa9, 0x2c,
	0x48, 0x15, 0xe2, 0xe0, 0x62, 0x09, 0x71, 0x0d, 0x0e, 0x11, 0x60, 0x10, 0x62, 0xe7, 0x62, 0x0e,
	0x77, 0x8c, 0x14, 0x60, 0x14, 0xe2, 0xe6, 0x62, 0x0f, 0x72, 0x0d, 0x8c, 0x07, 0x71, 0x98, 0x40,
	0x1c, 0x47, 0x67, 0x6f, 0x30, 0x87, 0x59, 0x48, 0x90, 0x8b, 0x17, 0x24, 0x13, 0xe4, 0xef, 0xef,
	0x1b, 0xef, 0xe3, 0x19, 0x1c, 0x22, 0xc0, 0x02, 0x12, 0x02, 0xc9, 0x23, 0x84, 0x58, 0x51, 0x54,
	0x79, 0xf9, 0x7b, 0xfa, 0x09, 0xb0, 0xa1, 0xa8, 0x02, 0x0b, 0xb1, 0x3b, 0x71, 0xad, 0x62, 0x62,
	0xcf, 0x4b, 0x2d, 0xd1, 0xcb, 0x2d, 0x4e, 0x4f, 0x62, 0x03, 0xbb, 0xd3, 0x18, 0x10, 0x00, 0x00,
	0xff, 0xff, 0xf9, 0xf6, 0xf6, 0x69, 0xb4, 0x00, 0x00, 0x00,
}
