// Code generated by protoc-gen-go. DO NOT EDIT.
// source: room.proto

package netmsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type UserInfo struct {
	Uuid                 string   `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserInfo) Reset()         { *m = UserInfo{} }
func (m *UserInfo) String() string { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()    {}
func (*UserInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{0}
}

func (m *UserInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserInfo.Unmarshal(m, b)
}
func (m *UserInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserInfo.Marshal(b, m, deterministic)
}
func (m *UserInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserInfo.Merge(m, src)
}
func (m *UserInfo) XXX_Size() int {
	return xxx_messageInfo_UserInfo.Size(m)
}
func (m *UserInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_UserInfo.DiscardUnknown(m)
}

var xxx_messageInfo_UserInfo proto.InternalMessageInfo

func (m *UserInfo) GetUuid() string {
	if m != nil {
		return m.Uuid
	}
	return ""
}

func (m *UserInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type RoomInfo struct {
	RoomIdx              int32    `protobuf:"varint,1,opt,name=roomIdx,proto3" json:"roomIdx,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ParticipateCount     int32    `protobuf:"varint,3,opt,name=participateCount,proto3" json:"participateCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{1}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomIdx() int32 {
	if m != nil {
		return m.RoomIdx
	}
	return 0
}

func (m *RoomInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RoomInfo) GetParticipateCount() int32 {
	if m != nil {
		return m.ParticipateCount
	}
	return 0
}

type AckRoomList struct {
	RoomList             []*RoomInfo `protobuf:"bytes,1,rep,name=roomList,proto3" json:"roomList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AckRoomList) Reset()         { *m = AckRoomList{} }
func (m *AckRoomList) String() string { return proto.CompactTextString(m) }
func (*AckRoomList) ProtoMessage()    {}
func (*AckRoomList) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{2}
}

func (m *AckRoomList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRoomList.Unmarshal(m, b)
}
func (m *AckRoomList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRoomList.Marshal(b, m, deterministic)
}
func (m *AckRoomList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRoomList.Merge(m, src)
}
func (m *AckRoomList) XXX_Size() int {
	return xxx_messageInfo_AckRoomList.Size(m)
}
func (m *AckRoomList) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRoomList.DiscardUnknown(m)
}

var xxx_messageInfo_AckRoomList proto.InternalMessageInfo

func (m *AckRoomList) GetRoomList() []*RoomInfo {
	if m != nil {
		return m.RoomList
	}
	return nil
}

type ReqRoomJoin struct {
	RoomIdx              int32    `protobuf:"varint,1,opt,name=roomIdx,proto3" json:"roomIdx,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRoomJoin) Reset()         { *m = ReqRoomJoin{} }
func (m *ReqRoomJoin) String() string { return proto.CompactTextString(m) }
func (*ReqRoomJoin) ProtoMessage()    {}
func (*ReqRoomJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{3}
}

func (m *ReqRoomJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRoomJoin.Unmarshal(m, b)
}
func (m *ReqRoomJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRoomJoin.Marshal(b, m, deterministic)
}
func (m *ReqRoomJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRoomJoin.Merge(m, src)
}
func (m *ReqRoomJoin) XXX_Size() int {
	return xxx_messageInfo_ReqRoomJoin.Size(m)
}
func (m *ReqRoomJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRoomJoin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRoomJoin proto.InternalMessageInfo

func (m *ReqRoomJoin) GetRoomIdx() int32 {
	if m != nil {
		return m.RoomIdx
	}
	return 0
}

func (m *ReqRoomJoin) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type AckRoomJoin struct {
	RoomIdx              int32       `protobuf:"varint,1,opt,name=roomIdx,proto3" json:"roomIdx,omitempty"`
	Title                string      `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Users                []*UserInfo `protobuf:"bytes,3,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AckRoomJoin) Reset()         { *m = AckRoomJoin{} }
func (m *AckRoomJoin) String() string { return proto.CompactTextString(m) }
func (*AckRoomJoin) ProtoMessage()    {}
func (*AckRoomJoin) Descriptor() ([]byte, []int) {
	return fileDescriptor_c5fd27dd97284ef4, []int{4}
}

func (m *AckRoomJoin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRoomJoin.Unmarshal(m, b)
}
func (m *AckRoomJoin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRoomJoin.Marshal(b, m, deterministic)
}
func (m *AckRoomJoin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRoomJoin.Merge(m, src)
}
func (m *AckRoomJoin) XXX_Size() int {
	return xxx_messageInfo_AckRoomJoin.Size(m)
}
func (m *AckRoomJoin) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRoomJoin.DiscardUnknown(m)
}

var xxx_messageInfo_AckRoomJoin proto.InternalMessageInfo

func (m *AckRoomJoin) GetRoomIdx() int32 {
	if m != nil {
		return m.RoomIdx
	}
	return 0
}

func (m *AckRoomJoin) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *AckRoomJoin) GetUsers() []*UserInfo {
	if m != nil {
		return m.Users
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "netmsg.UserInfo")
	proto.RegisterType((*RoomInfo)(nil), "netmsg.RoomInfo")
	proto.RegisterType((*AckRoomList)(nil), "netmsg.AckRoomList")
	proto.RegisterType((*ReqRoomJoin)(nil), "netmsg.ReqRoomJoin")
	proto.RegisterType((*AckRoomJoin)(nil), "netmsg.AckRoomJoin")
}

func init() { proto.RegisterFile("room.proto", fileDescriptor_c5fd27dd97284ef4) }

var fileDescriptor_c5fd27dd97284ef4 = []byte{
	// 240 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0x95, 0x86, 0xb4, 0xe1, 0xb2, 0x54, 0x16, 0x83, 0xc7, 0xca, 0x03, 0xaa, 0x10, 0xca,
	0x50, 0x46, 0xc4, 0x00, 0x4c, 0x45, 0x4c, 0x96, 0x78, 0x80, 0xd0, 0x5e, 0x2b, 0x0b, 0xec, 0x0b,
	0xf6, 0x45, 0xe2, 0x99, 0x78, 0x4a, 0x64, 0x07, 0x47, 0x42, 0x4c, 0x74, 0xfb, 0xef, 0x3f, 0x7f,
	0xbe, 0xdf, 0x3e, 0x00, 0x4f, 0x64, 0xdb, 0xde, 0x13, 0x93, 0x98, 0x3b, 0x64, 0x1b, 0x8e, 0x6a,
	0x03, 0xf5, 0x4b, 0x40, 0xbf, 0x75, 0x07, 0x12, 0x02, 0xce, 0x86, 0xc1, 0xec, 0x65, 0xb1, 0x2a,
	0xd6, 0xe7, 0x3a, 0xe9, 0xe8, 0xb9, 0xce, 0xa2, 0x9c, 0x8d, 0x5e, 0xd4, 0xea, 0x00, 0xb5, 0x26,
	0xb2, 0x89, 0x91, 0xb0, 0x88, 0xb7, 0x6e, 0xf7, 0x9f, 0x09, 0xab, 0x74, 0x2e, 0xc5, 0x05, 0x54,
	0x6c, 0xf8, 0x3d, 0xa3, 0x63, 0x21, 0xae, 0x60, 0xd9, 0x77, 0x9e, 0xcd, 0xce, 0xf4, 0x1d, 0xe3,
	0x23, 0x0d, 0x8e, 0x65, 0x99, 0xc0, 0x3f, 0xbe, 0xba, 0x85, 0xe6, 0x7e, 0xf7, 0x16, 0x47, 0x3d,
	0x9b, 0xc0, 0xe2, 0x1a, 0x6a, 0xff, 0xa3, 0x65, 0xb1, 0x2a, 0xd7, 0xcd, 0x66, 0xd9, 0x8e, 0xaf,
	0x68, 0x73, 0x1c, 0x3d, 0x9d, 0x50, 0x77, 0xd0, 0x68, 0xfc, 0x88, 0x8d, 0x27, 0x32, 0xee, 0xbf,
	0x39, 0x15, 0x4e, 0xb3, 0x4f, 0xc1, 0xc5, 0x25, 0x54, 0x43, 0x40, 0x1f, 0x64, 0xf9, 0x3b, 0x68,
	0xfe, 0x6b, 0x3d, 0xb6, 0x1f, 0xe0, 0x6b, 0xb6, 0x70, 0xc8, 0xad, 0x0d, 0xc7, 0xd7, 0x79, 0xda,
	0xcc, 0xcd, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0x91, 0x10, 0x4a, 0xd1, 0xa7, 0x01, 0x00, 0x00,
}
