// Code generated by protoc-gen-go. DO NOT EDIT.
// source: roomlist.proto

package netmsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RoomInfo struct {
	RoomIdx              int32    `protobuf:"varint,1,opt,name=roomIdx,proto3" json:"roomIdx,omitempty"`
	Title                string   `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	ParticipateCount     int32    `protobuf:"varint,3,opt,name=participateCount,proto3" json:"participateCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RoomInfo) Reset()         { *m = RoomInfo{} }
func (m *RoomInfo) String() string { return proto.CompactTextString(m) }
func (*RoomInfo) ProtoMessage()    {}
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e31d94b34335077, []int{0}
}

func (m *RoomInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoomInfo.Unmarshal(m, b)
}
func (m *RoomInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoomInfo.Marshal(b, m, deterministic)
}
func (m *RoomInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoomInfo.Merge(m, src)
}
func (m *RoomInfo) XXX_Size() int {
	return xxx_messageInfo_RoomInfo.Size(m)
}
func (m *RoomInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RoomInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RoomInfo proto.InternalMessageInfo

func (m *RoomInfo) GetRoomIdx() int32 {
	if m != nil {
		return m.RoomIdx
	}
	return 0
}

func (m *RoomInfo) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *RoomInfo) GetParticipateCount() int32 {
	if m != nil {
		return m.ParticipateCount
	}
	return 0
}

type AckRoomList struct {
	RoomList             []*RoomInfo `protobuf:"bytes,1,rep,name=roomList,proto3" json:"roomList,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AckRoomList) Reset()         { *m = AckRoomList{} }
func (m *AckRoomList) String() string { return proto.CompactTextString(m) }
func (*AckRoomList) ProtoMessage()    {}
func (*AckRoomList) Descriptor() ([]byte, []int) {
	return fileDescriptor_0e31d94b34335077, []int{1}
}

func (m *AckRoomList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckRoomList.Unmarshal(m, b)
}
func (m *AckRoomList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckRoomList.Marshal(b, m, deterministic)
}
func (m *AckRoomList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckRoomList.Merge(m, src)
}
func (m *AckRoomList) XXX_Size() int {
	return xxx_messageInfo_AckRoomList.Size(m)
}
func (m *AckRoomList) XXX_DiscardUnknown() {
	xxx_messageInfo_AckRoomList.DiscardUnknown(m)
}

var xxx_messageInfo_AckRoomList proto.InternalMessageInfo

func (m *AckRoomList) GetRoomList() []*RoomInfo {
	if m != nil {
		return m.RoomList
	}
	return nil
}

func init() {
	proto.RegisterType((*RoomInfo)(nil), "netmsg.RoomInfo")
	proto.RegisterType((*AckRoomList)(nil), "netmsg.AckRoomList")
}

func init() { proto.RegisterFile("roomlist.proto", fileDescriptor_0e31d94b34335077) }

var fileDescriptor_0e31d94b34335077 = []byte{
	// 176 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2b, 0xca, 0xcf, 0xcf,
	0xcd, 0xc9, 0x2c, 0x2e, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0x4b, 0x2d, 0xc9,
	0x2d, 0x4e, 0x57, 0x4a, 0xe3, 0xe2, 0x08, 0xca, 0xcf, 0xcf, 0xf5, 0xcc, 0x4b, 0xcb, 0x17, 0x92,
	0xe0, 0x62, 0x07, 0xa9, 0xf2, 0x4c, 0xa9, 0x90, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71,
	0x85, 0x44, 0xb8, 0x58, 0x4b, 0x32, 0x4b, 0x72, 0x52, 0x25, 0x98, 0x14, 0x18, 0x35, 0x38, 0x83,
	0x20, 0x1c, 0x21, 0x2d, 0x2e, 0x81, 0x82, 0xc4, 0xa2, 0x92, 0xcc, 0xe4, 0xcc, 0x82, 0xc4, 0x92,
	0x54, 0xe7, 0xfc, 0xd2, 0xbc, 0x12, 0x09, 0x66, 0xb0, 0x46, 0x0c, 0x71, 0x25, 0x6b, 0x2e, 0x6e,
	0xc7, 0xe4, 0x6c, 0x90, 0x55, 0x3e, 0x99, 0xc5, 0x25, 0x42, 0x3a, 0x5c, 0x1c, 0x45, 0x50, 0xb6,
	0x04, 0xa3, 0x02, 0xb3, 0x06, 0xb7, 0x91, 0x80, 0x1e, 0xc4, 0x45, 0x7a, 0x30, 0xe7, 0x04, 0xc1,
	0x55, 0x38, 0x71, 0xad, 0x62, 0x62, 0xcf, 0x4b, 0x2d, 0xd1, 0xcb, 0x2d, 0x4e, 0x4f, 0x62, 0x03,
	0xbb, 0xdf, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x3c, 0xe3, 0x4f, 0x6c, 0xd1, 0x00, 0x00, 0x00,
}
