// Code generated by protoc-gen-go. DO NOT EDIT.
// source: way.proto

package netmsg

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type AckWay struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AckWay) Reset()         { *m = AckWay{} }
func (m *AckWay) String() string { return proto.CompactTextString(m) }
func (*AckWay) ProtoMessage()    {}
func (*AckWay) Descriptor() ([]byte, []int) {
	return fileDescriptor_8313664ff05de314, []int{0}
}

func (m *AckWay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AckWay.Unmarshal(m, b)
}
func (m *AckWay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AckWay.Marshal(b, m, deterministic)
}
func (m *AckWay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AckWay.Merge(m, src)
}
func (m *AckWay) XXX_Size() int {
	return xxx_messageInfo_AckWay.Size(m)
}
func (m *AckWay) XXX_DiscardUnknown() {
	xxx_messageInfo_AckWay.DiscardUnknown(m)
}

var xxx_messageInfo_AckWay proto.InternalMessageInfo

func (m *AckWay) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AckWay) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*AckWay)(nil), "netmsg.AckWay")
}

func init() { proto.RegisterFile("way.proto", fileDescriptor_8313664ff05de314) }

var fileDescriptor_8313664ff05de314 = []byte{
	// 102 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x4f, 0xac, 0xd4,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xcb, 0x4b, 0x2d, 0xc9, 0x2d, 0x4e, 0x57, 0x32, 0xe2,
	0x62, 0x73, 0x4c, 0xce, 0x0e, 0x4f, 0xac, 0x14, 0x12, 0xe2, 0x62, 0xc9, 0x4b, 0xcc, 0x4d, 0x95,
	0x60, 0x54, 0x60, 0xd4, 0xe0, 0x0c, 0x02, 0xb3, 0x85, 0x44, 0xb8, 0x58, 0x53, 0x73, 0x13, 0x33,
	0x73, 0x24, 0x98, 0xc0, 0x82, 0x10, 0x8e, 0x13, 0xd7, 0x2a, 0x26, 0xf6, 0xbc, 0xd4, 0x12, 0xbd,
	0xdc, 0xe2, 0xf4, 0x24, 0x36, 0xb0, 0x71, 0xc6, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0x08,
	0x53, 0xd1, 0x5b, 0x00, 0x00, 0x00,
}
